// time out api call
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

// authentication
export const REQUEST_AUTHENTICATE_USER = "REQUEST_AUTHENTICATE_USER";
export const PROCESSING_AUTHENTICATE_USER = "PROCESSING_AUTHENTICATE_USER";
export const AUTHENTICATING = `AUTHENTICATING`;
export const AUTHENTICATED = `AUTHENTICATED`;
export const NOT_AUTHENTICATED = `NOT_AUTHENTICATED`;

export const REQUEST_REGISTER_USER = "REQUEST_REGISTER_USER";
export const PROCESSING_REGISTER_USER = "PROCESSING_REGISTER_USER";
export const REGISTER = `REGISTER`;
export const NOT_REGISTER = `NOT_REGISTER`;

export const REQUEST_LOGOUT_USER = "REQUEST_LOGOUT_USER";
export const PROCESSING_LOGOUT_USER = "PROCESSING_LOGOUT_USER";
export const LOGOUTD = `LOGOUTD`;
export const NOT_LOGOUTD = `NOT_LOGOUTD`;

// topics
export const REQUEST_TOPICS = "REQUEST_TOPICS";
export const API_LOAD_TOPICS = "API_LOAD_TOPICS";
export const LOAD_TOPICS_FAIL = "LOAD_TOPICS_FAIL";
export const LOAD_TOPICS_SUCCESS = "LOAD_TOPICS_SUCCESS";

// COURSES
// web
export const REQUEST_COURSES = "REQUEST_COURSES";
export const API_LOAD_COURSES = "API_LOAD_COURSES";
export const LOAD_COURSES_FAIL = "LOAD_COURSES_FAIL";
export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS";

export const REQUEST_USER_COURSE = "REQUEST_USER_COURSE";
export const API_LOAD_USER_COURSE = "API_LOAD_USER_COURSE";
export const LOAD_USER_COURSE_FAIL = "LOAD_USER_COURSE_FAIL";
export const LOAD_USER_COURSE_SUCCESS = "LOAD_USER_COURSE_SUCCESS";

export const REQUEST_CURRENT_USER = "REQUEST_CURRENT_USER";
export const API_LOAD_CURRENT_USER = "API_LOAD_CURRENT_USER";
export const LOAD_CURRENT_USER_FAIL = "LOAD_CURRENT_USER_FAIL";
export const LOAD_CURRENT_USER_SUCCESS = "LOAD_CURRENT_USER_SUCCESS";

export const REQUEST_COURSES_DETAIL = "REQUEST_COURSES_DETAIL";
export const API_LOAD_COURSES_DETAIL = "API_LOAD_COURSES_DETAIL";
export const LOAD_COURSES_DETAIL_FAIL = "LOAD_COURSES_DETAIL_FAIL";
export const LOAD_COURSES_DETAIL_SUCCESS = "LOAD_COURSES_DETAIL_SUCCESS";

// dashboard
export const REQUEST_COURSES_DASH = "REQUEST_COURSES_DASH";
export const API_LOAD_COURSES_DASH = "API_LOAD_COURSES_DASH";
export const LOAD_COURSES_FAIL_DASH = "LOAD_COURSES_FAIL_DASH";
export const LOAD_COURSES_SUCCESS_DASH = "LOAD_COURSES_SUCCESS_DASH";

export const REQUEST_CREATE_COURSE_DASH = "REQUEST_CREATE_COURSES_DASH";
export const API_CREATE_COURSE_DASH = "API_CREATE_COURSES_DASH";
export const CREATE_COURSE_FAIL_DASH = "CREATE_COURSES_FAIL_DASH";
export const CREATE_COURSE_SUCCESS_DASH = "CREATE_COURSES_SUCCESS_DASH";

export const REQUEST_UPDATE_COURSE_DASH = "REQUEST_UPDATE_COURSES_DASH";
export const API_UPDATE_COURSE_DASH = "API_UPDATE_COURSES_DASH";
export const UPDATE_COURSE_FAIL_DASH = "UPDATE_COURSES_FAIL_DASH";
export const UPDATE_COURSE_SUCCESS_DASH = "UPDATE_COURSES_SUCCESS_DASH";

export const REQUEST_JOBS_DASH = "REQUEST_JOBS_DASH";
export const API_LOAD_JOBS_DASH = "API_LOAD_JOBS_DASH";
export const LOAD_JOBS_FAIL_DASH = "LOAD_JOBS_FAIL_DASH";
export const LOAD_JOBS_SUCCESS_DASH = "LOAD_JOBS_SUCCESS_DASH";

export const REQUEST_LANGUAGES_DASH = "REQUEST_LANGUAGES_DASH";
export const API_LOAD_LANGUAGES_DASH = "API_LOAD_LANGUAGES_DASH";
export const LOAD_LANGUAGES_FAIL_DASH = "LOAD_LANGUAGES_FAIL_DASH";
export const LOAD_LANGUAGES_SUCCESS_DASH = "LOAD_LANGUAGES_SUCCESS_DASH";

export const REQUEST_SKILLS_DASH = "REQUEST_SKILLS_DASH";
export const API_LOAD_SKILLS_DASH = "API_LOAD_SKILLS_DASH";
export const LOAD_SKILLS_FAIL_DASH = "LOAD_SKILLS_FAIL_DASH";
export const LOAD_SKILLS_SUCCESS_DASH = "LOAD_SKILLS_SUCCESS_DASH";

export const REQUEST_CREATE_WEEK_DASH = "REQUEST_CREATE_WEEKS_DASH";
export const API_CREATE_WEEK_DASH = "API_CREATE_WEEKS_DASH";
export const CREATE_WEEK_FAIL_DASH = "CREATE_WEEKS_FAIL_DASH";
export const CREATE_WEEK_SUCCESS_DASH = "CREATE_WEEKS_SUCCESS_DASH";

export const REQUEST_WEEKS_DASH = "REQUEST_WEEKS_DASH";
export const API_LOAD_WEEKS_DASH = "API_LOAD_WEEKS_DASH";
export const LOAD_WEEKS_FAIL_DASH = "LOAD_WEEKS_FAIL_DASH";
export const LOAD_WEEKS_SUCCESS_DASH = "LOAD_WEEKS_SUCCESS_DASH";

export const REQUEST_BUY_COURSE = "REQUEST_BUY_COURSES";
export const API_BUY_COURSE = "API_BUY_COURSES";
export const BUY_COURSE_FAIL = "BUY_COURSES_FAIL";
export const BUY_COURSE_SUCCESS = "BUY_COURSES_SUCCESS";

export const REQUEST_DELETE_USERCOURSE = "REQUEST_DELETE_USERCOURSES";
export const API_DELETE_USERCOURSE = "API_DELETE_USERCOURSES";
export const DELETE_USERCOURSE_FAIL = "DELETE_USERCOURSES_FAIL";
export const DELETE_USERCOURSE_SUCCESS = "DELETE_USERCOURSES_SUCCESS";

export const REQUEST_UPDATE_USERCOURSE_BY_USERSID =
  "REQUEST_UPDATE_USERCOURSE_BY_USERSID";
export const API_UPDATE_USERCOURSE_BY_USERSID =
  "API_UPDATE_USERCOURSE_BY_USERSID";
export const UPDATE_USERCOURSE_BY_USERSID_FAIL =
  "UPDATE_USERCOURSE_BY_USERSIDS_FAIL";
export const UPDATE_USERCOURSE_BY_USERSID_SUCCESS =
  "UPDATE_USERCOURSE_BY_USERSIDS_SUCCESS";
